### ISSUE TITLE
2019で使えそうかチェックする＆思い出す

### ISSUE THREAD

**Issue by kiikura** [r-stack/rhd2018-ballot#2]

**Comment by kiikura** [comment]
ひとまず脆弱性もあるしバージョンをマイグレよう。

１年に一回しか勉強しないvue.jsでどこまでいけるか謎だが・・・

**Comment by kiikura** [comment]
おもむろに 

```
npm audit fix
```
はい grpc on gyp native build でこける

```
e.node --module_name=grpc_node --module_path=/Users/ken/git/ballot-labo/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown --napi_version=3 --node_abi_napi=napi' (1)
../deps/grpc/src/core/lib/backoff/backoff.cc:25:10: fatal error: 'src/core/lib/gpr/useful.h' file not found
#include "src/core/lib/gpr/useful.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/11.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/ken/git/ballot-l
```

**Comment by kiikura** [comment]
audit fix で細かく行こうかと思ったがやめよう。

```
(.venv) iikuraken-no-MacBook-Pro:ballot-labo ken$ npm ls grpc
rhd2018-ballot@1.0.0 /Users/ken/git/ballot-labo
└─┬ UNMET DEPENDENCY firebase@5.3.1
  └─┬ UNMET DEPENDENCY @firebase/firestore@0.6.1
    └── UNMET DEPENDENCY grpc@1.13.1 

```

**Comment by kiikura** [comment]
firebaseはどうせ新しい方がいいし、6.3.3まであげちゃう

結果

```
rhd2018-ballot@1.0.0 /Users/ken/git/ballot-labo
└─┬ firebase@6.3.3
  └─┬ @firebase/firestore@1.4.7
    └── grpc@1.22.2 

```

grpcも上がってハッピー

**Comment by kiikura** [comment]
@kmorihiro v2 ブランチは新しバージョンになってます。

**Comment by kiikura** [comment]
あ、勢い余ってtypescriptにしちゃってるので注意。（javascriptっぽい記述を続けてるので新し目のjavascriptならそのまま動くと思うが）

**Comment by kmorihiro** [comment]
thanks!! 参考にしました。
